### PR TITLE
Fix segfault on Mac, OpenGL being deprecated in favor of Metal since

### PR DESCRIPTION
**Pull request by devnexen**
years, it is not possible to dynamically load it.

### CODE REVIEW

**Comment by devnexen** [comment]
not sure if this is still viable plugin but just not to give false impression it has a chance to work on mac.

**Comment by ColinPitrat** [comment]
Have you built it on mac? I'm interested by feedback on it. Ideally I'd also like to be able to have a continuous build for it, potentially releasing a ready to use binary.

Compiling without HAVEGL should do the trick but I'm OK to add this if it works.

**Comment by devnexen** [comment]
In fact I build it on a mac indeed.

**Comment by devnexen** [comment]
> Have you built it on mac? I'm interested by feedback on it. 

Other than that, the default SDL2 mode works just fine as the audio too.

**Comment by ColinPitrat** [comment]
What does it give when selecting OpenGL video plugin with your change?
I think it'd be better to define HAVE_GL to be false if on mac. Something like ifdef __APPLE__ define HAVE_GL 0, or undef HAVE_GL

**Comment by devnexen** [comment]
> What does it give when selecting OpenGL video plugin with your change?
it segfaults. To explain the reason, since Mojave OpenGL is deprecated (still available tough but not as straight shared library anymore so you can t "dlopen" it like in the "old days"), passing libGL.dylib or null (means default path but for macOs case the said path set by SDL does not exist anymore) to SDL_GL_LoadLibrary does not solve it.

> I think it'd be better to define HAVE_GL to be false if on mac. Something like ifdef **APPLE** define HAVE_GL 0, or undef HAVE_GL

Your advice is valid, I agree.

**Comment by devnexen** [comment]
> What does it give when selecting OpenGL video plugin with your change?
Sorry I misread, the change just gave an error message but I followed your advice anyway.

**Comment by ColinPitrat** [comment]
I'm trying to setup a macos build using GitHub Actions. This reproduces the issue: https://github.com/ColinPitrat/caprice32/actions

I think `make WITHOUT_GL` would be the right approach, but deducing it without the option for Mac would be nice too.

**Comment by ColinPitrat** [comment]
I started a Mac build with GitHub actions and then got caught it and forgot that the purpose was to test this :-)
Taking a look at removing WITHOUT_GL now.

**Comment by ColinPitrat** [comment]
I pushed a different fix in https://github.com/ColinPitrat/caprice32/commit/79f30e31cc78a7a4875e1574542fdbe8f39aad34

Sorry if this feels a bit NIH, it's just that HAVE_GL is used in many places and I wanted to ensure they are all activated or deactivated together.

**Comment by devnexen** [comment]
I saw it :) fine by me

**Comment by ColinPitrat** [comment]
There's now a MacOS bundle attached to latest release (only latest for now). I think it should work fine. If you have a mac, can you give it a try? There are probably improvements that can be done (icon, metadata, etc ...)

**Comment by devnexen** [comment]
I m guessing it s for Mac Intel (eventually for Rosetta) ?

**Comment by ColinPitrat** [comment]
Yes, I suppose so :)

Le sam. 10 avr. 2021 à 18:22, David CARLIER ***@***.***> a
écrit :

**Comment by devnexen** [comment]
Yes it is just checked, you might need to build what is called universal binary (if that is possible) https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by ColinPitrat** [comment]
That's what I use: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I'll look into universal builds.

**Comment by devnexen** [comment]
Sure ; if not it work ok under Rosetta ;-)

**Pull request closed without merging**
