### PR TITLE
Add debian packaging

### PR DESCRIPTION
**Pull request by nudgegoonies**
I added debian packaging. The package is not yet perfectly lintian clean regarding the copyright file. Then there are issues with the configfile. Users have to copy /etc/cap32.cfg to ~/.cap32.cfg first until they can make changes from the ui. Without the .cap32.cfg the emulator does not start. Also a default directory for the caprice snaptshots, etc. files is needed. I created a quilt patch to patch the debian package only to use ~./caprice and subdirectories. But they have to be created manually by the users. Starting caprice does not create them automatically.

### CODE REVIEW

**Comment by ColinPitrat** [comment]
Thanks this is great !

Is the `debian/` subdirectory the usual way to proceed ? Is it possible to move it to a subdirectory (e.g `pkg`, `packages`, `packaging` ...) to avoid cluttering the top directory of the repo in case other types of packages are included in the future ? Or is it the usual way to put it in the top dir ?

I open an issue for your remark considering the configuration file, the .caprice dir and the automatic creation of directories.

**Comment by ColinPitrat** [comment]
Note: I think the only directory mandatory for the emulator to start is the `rom` directory.
However, easing the handling of the other directories would still be nice.

**Comment by nudgegoonies** [comment]
Hi Colin. Thank you very much for your answer and creating the other issue!

For a real debian package the debian directory has its own git repository. But for projects on github which are not in real debian yet having the debian directory in the project seems common. I will have a look if it is possible to do it different.

One Option is to keep it as it is, the debian directory in root folder of the project, is to adjust the package that no orig.tar.gz is needed. This option seems easy to me. At the moment the orig.tar.gz has to be created manual. This is bad.

Another one is to keep the debian directory external in an own repository and providing a script which fetches the caprice repo, builds the orig.tar.gz, and then builds and packages the whole thing. This seem also easy.

I already have seen projects where the packaging is done from a special subdirectory. But i don't know how this works and in that case i have to lookout for examples first to see how this works and if these examples use the standard debian packaging tools or if they use something like fpm, etc.

I will continue this weekend.

**Comment by ColinPitrat** [comment]
OK, I'll integrate it as-is.
Another improvement that would be nice is to validate the package creation in the continuous build on travis.

**Comment by nudgegoonies** [comment]
Thank you very much. I have made some more changes and will open a new merge request and comment there.

**Pull request merged**
